# =============================================================================
# ARQUIVO DE CONFIGURAÇÃO DEFINITIVO PARA NETLIFY
# =============================================================================

[build]
  # O comando é executado a partir da RAIZ do projeto.
  command = "npm install && (cd client && npm install && npm run build)"
  
  # Diretório contendo o resultado do build do Next.js, relativo à raiz.
  publish = "client/.next"
  
  # Diretório contendo as funções serverless, relativo à raiz.
  functions = "netlify/functions"

# Define a versão do Node.js para todo o ambiente de build.
[build.environment]
  NODE_VERSION = "20.11.1" # Usando uma versão LTS (Long-Term Support) estável.

# Plugin essencial para otimizar o deploy de sites Next.js na Netlify.
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Regras de cabeçalhos (Headers) para a API.
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, GET, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"