# =============================================================================
# ARQUIVO DE CONFIGURAÇÃO DEFINITIVO PARA NETLIFY
# =============================================================================

[build]
  # O comando agora é uma sequência que instala as dependências em cada pasta específica.
  # Passo 1: Entra na pasta de funções e instala suas dependências.
  # Passo 2: Entra na pasta do cliente, instala suas dependências e faz o build.
  command = "(cd netlify/functions && npm install) && (cd client && npm install && npm run build)"

  # Diretório de publicação do frontend.
  publish = "client/.next"

  # Diretório das funções serverless.
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.11.1" # Usando uma versão LTS estável.

[[plugins]]
  package = "@netlify/plugin-nextjs"