# Arquivo: netlify.toml (CORRIGIDO)

[build]
  # O 'base' já nos coloca no diretório 'client', então o comando
  # não precisa mais do 'cd client'.
  base = "client"
  command = "npm install && npm run build"
  # O diretório de publicação é relativo ao 'base'.
  publish = ".next"
  # As funções são relativas à raiz do repositório.
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers de CORS globais para todas as funções.
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"