# Arquivo: netlify.toml (VERSÃO CORRIGIDA E FINAL)

[build]
  # 1. O comando é executado a partir da raiz do projeto.
  # 2. Primeiro, ele instala as dependências das funções (do netlify/functions/package.json).
  # 3. Depois, ele entra na pasta 'client', instala as dependências do frontend E as devDependencies, e faz o build.
  command = "npm install && (cd client && npm install && npm run build)"
  
  # O caminho de publicação é relativo à raiz.
  publish = "client/.next"
  
  # O caminho das funções é relativo à raiz.
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers de CORS para as funções.
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"