# Comando para TRAE: Sobrescrever o arquivo 'netlify.toml' com este conteúdo.

[build]
  # Comando de build agora é executado a partir da raiz do projeto.
  command = "cd client && npm install && npm run build"
  # Caminho de publicação corrigido para ser relativo à raiz.
  publish = "client/.next"
  # Caminho das funções corrigido para ser relativo à raiz.
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers de CORS globais para todas as funções.
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"