# =============================================================================
# ARQUIVO DE CONFIGURAÇÃO DEFINITIVO PARA NETLIFY
# =============================================================================

[build]
  # O comando agora instala as dependências em cada pasta específica,
  # garantindo que as devDependencies do client sejam incluídas.
  command = "(cd netlify/functions && npm install) && (cd client && npm install && npm run build)"

  publish = "client/.next"
  functions = "netlify/functions"

[build.environment]
  # Define a versão do Node.js compatível com suas dependências.
  NODE_VERSION = "22.12.0" 
  # Esta flag força o npm a instalar TODAS as dependências, incluindo as de desenvolvimento.
  NPM_FLAGS = "--include=dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"