[build]
  # Agora o comando roda dentro de client direto, sem duplicar caminho.
  base = "client"
  command = "npm install && npm run build"
  publish = ".next"
  functions = "../netlify/functions"

[build.environment]
  NODE_VERSION = "22.12.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, GET, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
