# ARQUIVO DE CONFIGURAÇÃO FINAL E SIMPLIFICADO

[build]
  command = "cd client && npm install && npm run build"
  publish = "client/.next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22.12.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"