services:
  - type: web
    name: church-backend
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        sync: false

  - type: web
    name: church-frontend
    env: node
    rootDir: client
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NODE_VERSION
        value: 18