services:
  - type: web
    name: gestao-igreja-backend
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        value: https://gestao-igreja-frontend.onrender.com

  - type: web
    name: gestao-igreja-frontend
    env: node
    rootDir: client
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://gestao-igreja-backend.onrender.com/api
      - key: NODE_VERSION
        value: 20